{% set name = "envs" %}
{% set version = "1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/envs-{{ version }}.tar.gz
  sha256: 9d8435c6985d1cdd68299e04c58e2bdb8ae6cf66b2596a8079e6f9a93f2a0398

build:
  number: 1
  noarch: python
  entry_points:
    - envs = envs.cli:envs
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - click
    - jinja2
    - terminaltables
    - python >={{ python_min }},<4.0

test:
  requires:
    - click
    - jinja2
    - terminaltables  
    - python {{ python_min }}
  imports:
    - envs
  commands:
    - pip check
    - envs --help
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/bjinwright/envs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy access of environment variables from Python with support for strings, booleans, list, tuples, and dicts.
  dev_url: https://github.com/bjinwright/envs

extra:
  recipe-maintainers:
    - mxr-conda
